<a href="https://colab.research.google.com/github/shahrukhalam1011-unisa/Pytorch_learning_free_code_camp/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating tensors

Pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix[1]

tensor([ 9, 10])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
Tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [16]:
Tensor2=torch.tensor([[[1,2,3,3,3],[2,3,5,3,4],[1,2,1,2,5],[2,3,5,6,1]]])

In [17]:
Tensor2

tensor([[[1, 2, 3, 3, 3],
         [2, 3, 5, 3, 4],
         [1, 2, 1, 2, 5],
         [2, 3, 5, 6, 1]]])

In [18]:
Tensor2.shape

torch.Size([1, 4, 5])

### Random tensors

Required since to start with random numbers and update to better represent the data

In [19]:
## Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7839, 0.6123, 0.6421, 0.1855],
        [0.6824, 0.7522, 0.3223, 0.1972],
        [0.0625, 0.4178, 0.1824, 0.4856]])

In [20]:
random_tensor2=torch.rand(2,3,10)

In [21]:
random_tensor2

tensor([[[0.9414, 0.2404, 0.9403, 0.2010, 0.4468, 0.9530, 0.9403, 0.7295,
          0.9875, 0.3274],
         [0.5663, 0.1067, 0.5395, 0.3691, 0.9086, 0.2341, 0.6668, 0.3225,
          0.2445, 0.5428],
         [0.0866, 0.0335, 0.6256, 0.2811, 0.4344, 0.0837, 0.9468, 0.7825,
          0.9342, 0.0318]],

        [[0.9215, 0.0972, 0.3052, 0.9832, 0.5147, 0.0328, 0.5931, 0.3399,
          0.3223, 0.0519],
         [0.8622, 0.5986, 0.9578, 0.2209, 0.0924, 0.1322, 0.8529, 0.0706,
          0.3092, 0.0192],
         [0.8094, 0.0942, 0.2891, 0.5935, 0.7234, 0.6312, 0.2069, 0.9153,
          0.9223, 0.3406]]])

In [22]:
random_tensor2.shape

torch.Size([2, 3, 10])

In [23]:
random_tensor2.ndim

3

In [24]:
random_tensor3=torch.rand(200,344,100)

In [25]:
random_tensor3

tensor([[[0.6750, 0.3453, 0.3191,  ..., 0.3016, 0.1116, 0.7388],
         [0.2639, 0.4038, 0.8624,  ..., 0.1663, 0.8354, 0.9450],
         [0.1608, 0.2633, 0.7111,  ..., 0.3518, 0.2133, 0.0678],
         ...,
         [0.5062, 0.4353, 0.7915,  ..., 0.5657, 0.9590, 0.7765],
         [0.3150, 0.7211, 0.7790,  ..., 0.5911, 0.0196, 0.8064],
         [0.3231, 0.0300, 0.3103,  ..., 0.9203, 0.2879, 0.6538]],

        [[0.5463, 0.2624, 0.1212,  ..., 0.0893, 0.5644, 0.0623],
         [0.8294, 0.4541, 0.8981,  ..., 0.7381, 0.1002, 0.7651],
         [0.3162, 0.9681, 0.6299,  ..., 0.0674, 0.1138, 0.9013],
         ...,
         [0.9498, 0.7043, 0.3835,  ..., 0.5424, 0.2573, 0.4094],
         [0.5010, 0.2786, 0.3741,  ..., 0.5131, 0.9634, 0.6125],
         [0.9998, 0.9535, 0.4412,  ..., 0.5212, 0.6840, 0.9584]],

        [[0.5527, 0.6595, 0.2727,  ..., 0.5469, 0.1467, 0.2228],
         [0.2842, 0.6149, 0.5346,  ..., 0.7271, 0.7973, 0.1388],
         [0.6183, 0.9216, 0.9487,  ..., 0.0862, 0.7953, 0.

In [26]:
random_tensor3.shape

torch.Size([200, 344, 100])

In [27]:
random_tensor3.ndim

3

In [28]:
random_tensor4=torch.rand(3,2,5,5)

In [29]:
random_tensor4

tensor([[[[0.4822, 0.2266, 0.1152, 0.4109, 0.6226],
          [0.3379, 0.6110, 0.5411, 0.8187, 0.0480],
          [0.3473, 0.9801, 0.2238, 0.2990, 0.9475],
          [0.9783, 0.5429, 0.6008, 0.7921, 0.4741],
          [0.1507, 0.7087, 0.5073, 0.5730, 0.8732]],

         [[0.9000, 0.6234, 0.4722, 0.7800, 0.4359],
          [0.7004, 0.3543, 0.7210, 0.7479, 0.4441],
          [0.4414, 0.3604, 0.6866, 0.3234, 0.3747],
          [0.5274, 0.6643, 0.5177, 0.0302, 0.7886],
          [0.7997, 0.3120, 0.9154, 0.0206, 0.7422]]],


        [[[0.2737, 0.1716, 0.8955, 0.7367, 0.6262],
          [0.4939, 0.2738, 0.9429, 0.8602, 0.4562],
          [0.9349, 0.1375, 0.4190, 0.7371, 0.7868],
          [0.3640, 0.8291, 0.1455, 0.1877, 0.6125],
          [0.6593, 0.3297, 0.3007, 0.6155, 0.0090]],

         [[0.3228, 0.6025, 0.6125, 0.1537, 0.1443],
          [0.5566, 0.5338, 0.8721, 0.3147, 0.8521],
          [0.1705, 0.4725, 0.5991, 0.3028, 0.8197],
          [0.1203, 0.1728, 0.9366, 0.1303, 0.1578],
    

In [30]:
random_tensor4.ndim

4

In [31]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) # colour channel, height, width

In [32]:
random_image_size_tensor

tensor([[[0.0990, 0.8376, 0.7480,  ..., 0.8966, 0.0685, 0.7718],
         [0.7582, 0.6587, 0.5480,  ..., 0.8331, 0.9925, 0.4622],
         [0.8557, 0.2572, 0.7452,  ..., 0.4837, 0.2956, 0.2146],
         ...,
         [0.4965, 0.6575, 0.0147,  ..., 0.2245, 0.7678, 0.3394],
         [0.0730, 0.4730, 0.3568,  ..., 0.5717, 0.7102, 0.0067],
         [0.1346, 0.5480, 0.4063,  ..., 0.2891, 0.2758, 0.8537]],

        [[0.4481, 0.4103, 0.8377,  ..., 0.9730, 0.1508, 0.3527],
         [0.2602, 0.7374, 0.7420,  ..., 0.2158, 0.3177, 0.4894],
         [0.5899, 0.0444, 0.3682,  ..., 0.4904, 0.9236, 0.2512],
         ...,
         [0.4157, 0.3646, 0.8851,  ..., 0.7764, 0.8023, 0.8931],
         [0.7895, 0.1458, 0.5966,  ..., 0.4296, 0.5154, 0.1883],
         [0.3813, 0.0331, 0.8583,  ..., 0.1727, 0.6657, 0.8898]],

        [[0.3085, 0.7174, 0.7720,  ..., 0.5755, 0.7577, 0.8546],
         [0.4454, 0.4230, 0.5690,  ..., 0.0962, 0.9328, 0.8802],
         [0.6858, 0.6259, 0.9223,  ..., 0.3756, 0.4418, 0.

### Zeroes and ones

In [33]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,224,224))
ones=torch.ones(size=(3,224,224))

In [34]:
zeros
ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [35]:
zeros*random_image_size_tensor

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [36]:
ones*random_image_size_tensor

tensor([[[0.0990, 0.8376, 0.7480,  ..., 0.8966, 0.0685, 0.7718],
         [0.7582, 0.6587, 0.5480,  ..., 0.8331, 0.9925, 0.4622],
         [0.8557, 0.2572, 0.7452,  ..., 0.4837, 0.2956, 0.2146],
         ...,
         [0.4965, 0.6575, 0.0147,  ..., 0.2245, 0.7678, 0.3394],
         [0.0730, 0.4730, 0.3568,  ..., 0.5717, 0.7102, 0.0067],
         [0.1346, 0.5480, 0.4063,  ..., 0.2891, 0.2758, 0.8537]],

        [[0.4481, 0.4103, 0.8377,  ..., 0.9730, 0.1508, 0.3527],
         [0.2602, 0.7374, 0.7420,  ..., 0.2158, 0.3177, 0.4894],
         [0.5899, 0.0444, 0.3682,  ..., 0.4904, 0.9236, 0.2512],
         ...,
         [0.4157, 0.3646, 0.8851,  ..., 0.7764, 0.8023, 0.8931],
         [0.7895, 0.1458, 0.5966,  ..., 0.4296, 0.5154, 0.1883],
         [0.3813, 0.0331, 0.8583,  ..., 0.1727, 0.6657, 0.8898]],

        [[0.3085, 0.7174, 0.7720,  ..., 0.5755, 0.7577, 0.8546],
         [0.4454, 0.4230, 0.5690,  ..., 0.0962, 0.9328, 0.8802],
         [0.6858, 0.6259, 0.9223,  ..., 0.3756, 0.4418, 0.

### Creating a range of tensors and tensors-like

In [37]:
#Use torch.arange()
torch.arange(1,11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [38]:
one_to_ten=torch.arange(start=1, end=10, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [39]:
#Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)

In [40]:
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [41]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16 #what datatype is the tensor
                             , device=None # Device tensor is on
                             ,
                             requires_grad=False # Whether to track gradient for the tensor
                             )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [42]:
new_int_tensor_train=torch.rand(3,4)

In [43]:
new_int_tensor_train

tensor([[0.5298, 0.9242, 0.0989, 0.3759],
        [0.5723, 0.6366, 0.6136, 0.5692],
        [0.7739, 0.1878, 0.8752, 0.2600]])

In [44]:
# Find details of tensor

print(f"Datatype is: {new_int_tensor_train.dtype}")
print(f"Shape is: {new_int_tensor_train.shape}")
print(f"Device is: {new_int_tensor_train.device}")

Datatype is: torch.float32
Shape is: torch.Size([3, 4])
Device is: cpu


In [45]:
# Change data type using .to
change_new_int_tensor_train=new_int_tensor_train.to(torch.float16)
change_new_int_tensor_train

tensor([[0.5298, 0.9243, 0.0989, 0.3760],
        [0.5723, 0.6367, 0.6138, 0.5693],
        [0.7739, 0.1879, 0.8750, 0.2600]], dtype=torch.float16)

In [52]:
# Change data type using .type
change_new_int_tensor_train=new_int_tensor_train.type(torch.float16)
change_new_int_tensor_train

tensor([[0.5298, 0.9243, 0.0989, 0.3760],
        [0.5723, 0.6367, 0.6138, 0.5693],
        [0.7739, 0.1879, 0.8750, 0.2600]], dtype=torch.float16)

In [53]:
# Multiply different types of tensor
new_int_tensor_train*change_new_int_tensor_train

tensor([[0.2807, 0.8542, 0.0098, 0.1413],
        [0.3275, 0.4053, 0.3766, 0.3241],
        [0.5989, 0.0353, 0.7658, 0.0676]])

In [56]:
int_32_tensor=new_int_tensor_train.type(torch.int32)
int_32_tensor

tensor([[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]], dtype=torch.int32)

In [57]:
int_32_tensor*new_int_tensor_train

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

### Getting information from tensors

1. Tensors not the right datatype - to get datatype from a tensor, can use tensor.dtype
2. Tensors not the right shape - to get shape from a tensor, can use tensor.shape
3. Tensors not on the right device - to get device from a tensor, can use tensor.device

In [58]:
# Create a tensor
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.0618, 0.0365, 0.5673, 0.9360],
        [0.0527, 0.8873, 0.7550, 0.3937],
        [0.9014, 0.1102, 0.6851, 0.1841]])

In [60]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Device of tensor: {some_tensor.device}")

tensor([[0.0618, 0.0365, 0.5673, 0.9360],
        [0.0527, 0.8873, 0.7550, 0.3937],
        [0.9014, 0.1102, 0.6851, 0.1841]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device of tensor: cpu


### Manipulating Tensors (tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [61]:
# Create a tensor
tensor=torch.tensor([1,2,3])
tensor+10

tensor([11, 12, 13])

In [62]:
# Multiply tensor by 10
tensor*10

tensor([10, 20, 30])

In [63]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [67]:
# In-built functions
print(torch.mul(tensor,10))
print(torch.add(tensor,10))
print(torch.sub(tensor,10))

tensor([10, 20, 30])
tensor([11, 12, 13])
tensor([-9, -8, -7])


### Matrix multiplication

Two ways:
1. Element-wise multiplication
2. Matrix Multiplication




In [47]:
tensor1=torch.rand(3,6,5)
tensor2=torch.rand(1,5,7)
tensor1
tensor2

tensor([[[0.8109, 0.8510, 0.5383, 0.5100, 0.2927, 0.2810, 0.2101],
         [0.6885, 0.9914, 0.7878, 0.9847, 0.1455, 0.1323, 0.6543],
         [0.2391, 0.3675, 0.9204, 0.8635, 0.5848, 0.4461, 0.3899],
         [0.3472, 0.4189, 0.0814, 0.3527, 0.2103, 0.3353, 0.5348],
         [0.3142, 0.5240, 0.6943, 0.0616, 0.9021, 0.2181, 0.8345]]])

In [69]:
#Matrix multiplication
%%time
product_ten=torch.matmul(tensor1, tensor2)
product_ten

CPU times: user 504 µs, sys: 28 µs, total: 532 µs
Wall time: 379 µs


tensor([[[1.1455, 1.4307, 1.3856, 0.8548, 1.2849, 0.6549, 1.1952],
         [1.1170, 1.4926, 1.4705, 1.4252, 1.0206, 0.7166, 1.3051],
         [0.9486, 1.3143, 1.5799, 1.5235, 1.0678, 0.7589, 1.2257],
         [1.0574, 1.2926, 1.0014, 0.9481, 0.7804, 0.5726, 0.9689],
         [1.2735, 1.7156, 1.5751, 1.4336, 1.2022, 0.7646, 1.5879],
         [1.3360, 1.7341, 1.6082, 1.6297, 1.2008, 0.9197, 1.5344]],

        [[1.3166, 1.6960, 1.8896, 1.5317, 1.3277, 0.7968, 1.2762],
         [1.4320, 1.8510, 1.6638, 1.8190, 0.8688, 0.7323, 1.2827],
         [0.3491, 0.4670, 0.4030, 0.5210, 0.2626, 0.2651, 0.4428],
         [1.4715, 2.0092, 1.9175, 1.9212, 1.3086, 0.9239, 1.8320],
         [1.5929, 2.0696, 2.0167, 1.7312, 1.2565, 0.7379, 1.4553],
         [1.3293, 1.8030, 1.8501, 1.5146, 1.2528, 0.6735, 1.4775]],

        [[1.6213, 2.1042, 1.7014, 1.9415, 0.9867, 0.8528, 1.6182],
         [1.0657, 1.5379, 1.6364, 1.3131, 1.2388, 0.6388, 1.5488],
         [0.9382, 1.4024, 1.8301, 1.3144, 1.4736, 0.7167, 

In [70]:
changed_to_int32=product_ten.to(torch.int32)
changed_to_int32

tensor([[[1, 1, 1, 0, 1, 0, 1],
         [1, 1, 1, 1, 1, 0, 1],
         [0, 1, 1, 1, 1, 0, 1],
         [1, 1, 1, 0, 0, 0, 0],
         [1, 1, 1, 1, 1, 0, 1],
         [1, 1, 1, 1, 1, 0, 1]],

        [[1, 1, 1, 1, 1, 0, 1],
         [1, 1, 1, 1, 0, 0, 1],
         [0, 0, 0, 0, 0, 0, 0],
         [1, 2, 1, 1, 1, 0, 1],
         [1, 2, 2, 1, 1, 0, 1],
         [1, 1, 1, 1, 1, 0, 1]],

        [[1, 2, 1, 1, 0, 0, 1],
         [1, 1, 1, 1, 1, 0, 1],
         [0, 1, 1, 1, 1, 0, 1],
         [0, 1, 0, 1, 0, 0, 1],
         [1, 1, 1, 1, 0, 0, 1],
         [1, 1, 1, 1, 1, 0, 1]]], dtype=torch.int32)

### Most common error in Deep Learning: Shape error

1. The inner dimension must match
2. The resulting matrix would be the outer dimension
3. In case, the tensors violate rules 1 and 2, tensor manipulation i.e. transpose can be used. It works by switching axes.

In [90]:
Tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
Tensor_B=torch.tensor([[5,3],[2,6],[1,8]])
Tensor_A
Tensor_B
Tensor_C=torch.matmul(Tensor_A,Tensor_B).shape
Tensor_C

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [72]:
# To resolve the above use transpose
Trans_Tensor_B=Tensor_B.T
Trans_Tensor_B

tensor([[5, 2, 1],
        [3, 6, 8]])

In [94]:
Tensor_C=torch.matmul(Tensor_A,Trans_Tensor_B)
print(Tensor_C)
Tensor_C.shape

tensor([[11, 14, 17],
        [27, 30, 35],
        [43, 46, 53]])


torch.Size([3, 3])

In [96]:
# The matrix multiplication operation works when tensor_B is transposed
print(f"Tensor_A is {Tensor_A}")
print(f"Tensor_B is {Tensor_B}")
print(f"Original shapes: Tensor_A = {Tensor_A.shape}, Tensor_B = {Tensor_B.shape}")
print(f"New shapes: Tensor_A = {Tensor_A.shape} (same as above), Tensor_B.T = {Tensor_B.T.shape}")
print(f"Multiplying: {Tensor_A.shape} * {Tensor_B.T.shape} <- inner dimensions match")
print("Output:\n")
output = torch.matmul(Tensor_A, Tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Tensor_A is tensor([[1, 2],
        [3, 4],
        [5, 6]])
Tensor_B is tensor([[5, 3],
        [2, 6],
        [1, 8]])
Original shapes: Tensor_A = torch.Size([3, 2]), Tensor_B = torch.Size([3, 2])
New shapes: Tensor_A = torch.Size([3, 2]) (same as above), Tensor_B.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match
Output:

tensor([[11, 14, 17],
        [27, 30, 35],
        [43, 46, 53]])

Output shape: torch.Size([3, 3])


### Finding the min, max, mean, sum etc (tensor aggragation)

In [98]:
# Create a tensor
x=torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [99]:
# Find the min
torch.min(x)

tensor(0)

In [100]:
# Find the max
torch.max(x)

tensor(90)

In [101]:
# Find the mean - note: the torch.mean() function requires a tensor of float32 datatype to work
torch.mean(x)

RuntimeError: mean(): could not infer output dtype. Input dtype must be either a floating point or complex dtype. Got: Long

In [103]:
torch.mean(x.type(torch.float32))

tensor(45.)

In [104]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

### Position of Tensor elements (pixels, data etc)

In [111]:
tensor_4D=torch.rand(1,6,2,3)
tensor_4D

tensor([[[[0.5262, 0.8931, 0.7489],
          [0.2914, 0.7278, 0.9745]],

         [[0.5455, 0.6630, 0.8920],
          [0.0941, 0.6507, 0.9489]],

         [[0.7265, 0.3320, 0.3487],
          [0.4089, 0.1469, 0.9127]],

         [[0.0548, 0.5710, 0.9995],
          [0.4366, 0.6798, 0.4537]],

         [[0.7241, 0.3830, 0.6676],
          [0.3865, 0.7871, 0.6832]],

         [[0.5090, 0.4017, 0.4361],
          [0.9622, 0.9966, 0.2176]]]])

In [112]:
tensor_4D.shape

torch.Size([1, 6, 2, 3])

In [113]:
tensor_4D.ndim

4

In [117]:
# Position in tensor that has the minimum value
position_min=tensor_4D.argmin()

In [118]:
position_min

tensor(18)

In [119]:
# Position in tensor that has the maximum value
position_max=tensor_4D.argmax()
position_max

tensor(20)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [122]:
# Let's create a tensor
import torch
x=torch.arange(2., 10.)
x, x.shape, x.ndim

(tensor([2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([8]), 1)

In [123]:
# Add an extra dimension (note that the size must match i.e. 4*2 or 2*4 = 8)
x_reshaped=x.reshape(4,2)
print(x_reshaped, x_reshaped.shape, x_reshaped.ndim)
x_reshaped2=x.reshape(2,4)
print(x_reshaped2, x_reshaped2.shape, x_reshaped2.ndim)

tensor([[2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([4, 2]) 2
tensor([[2., 3., 4., 5.],
        [6., 7., 8., 9.]]) torch.Size([2, 4]) 2


In [127]:
# Change the view
z=x.view(4,2)
z, z.shape, z.ndim

(tensor([[2., 3.],
         [4., 5.],
         [6., 7.],
         [8., 9.]]),
 torch.Size([4, 2]),
 2)

In [133]:
# Changing z changes x (due to view of a tensor sharing same memory)
z[:,0]=5
z, x, z.ndim, z.shape, x.ndim, x.shape

(tensor([[5., 3.],
         [5., 5.],
         [5., 7.],
         [5., 9.]]),
 tensor([5., 3., 5., 5., 5., 7., 5., 9.]),
 2,
 torch.Size([4, 2]),
 1,
 torch.Size([8]))

In [130]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 3., 5., 5., 5., 7., 5., 9.],
        [5., 3., 5., 5., 5., 7., 5., 9.]])

In [84]:
y_stacked=torch.stack([x,x,x,x], dim=1)
y_stacked

tensor([[5., 5., 5., 5.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [137]:
# torch.squeeze() - removes all 1 dimension from a target tensor
x_reshaped3=x.reshape(1,8)
x_reshaped3, x_reshaped3.shape, x_reshaped3.ndim

(tensor([[5., 3., 5., 5., 5., 7., 5., 9.]]), torch.Size([1, 8]), 2)

In [138]:
x_reshaped3.squeeze()

tensor([5., 3., 5., 5., 5., 7., 5., 9.])

In [144]:
# Note that squeeze has removed the single dimension, leaving with only one dimension of 8 elements
print(x_reshaped3.squeeze().shape)
print(x_reshaped3.squeeze().ndim)

torch.Size([8])
1


In [145]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped3}")
print(f"Previous shape: {x_reshaped3.shape}")

# Remove extra dimension from x_reshaped3
x_squeezed = x_reshaped3.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 3., 5., 5., 5., 7., 5., 9.]])
Previous shape: torch.Size([1, 8])

New tensor: tensor([5., 3., 5., 5., 5., 7., 5., 9.])
New shape: torch.Size([8])


In [147]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 3., 5., 5., 5., 7., 5., 9.])
Previous shape: torch.Size([8])

New tensor: tensor([[5., 3., 5., 5., 5., 7., 5., 9.]])
New shape: torch.Size([1, 8])


In [151]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(3,224,224)) # [colour_channels, height, width]
# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2,1,0) # shifts axis 0->2, 1->0, 2->0
print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([3, 224, 224])
New shape: torch.Size([224, 224, 3])


In [152]:
x_original[0,0,0]=982034
x_original[0,0,0], x_permuted[0,0,0]

(tensor(982034.), tensor(982034.))

### Indexing (selecting data from tensors)
Indexing with PyTorch is similar to indexing with NumPy

In [157]:
# Create a tensor
import torch
x=torch.arange(1,10)
x, x.shape

(tensor([1, 2, 3, 4, 5, 6, 7, 8, 9]), torch.Size([9]))

In [158]:
x=x.reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [159]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [164]:
# Let's index on the middle bracket (dim=1)
x[0][0] # or use x[0,0]
x[0,0]

tensor([1, 2, 3])

In [165]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0] # or use x[0,0,0]

tensor(1)

In [166]:
x[0][2][2] # or use x[0,2,2]

tensor(9)

In [167]:
# you can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [168]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [169]:
# Get all values of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [170]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0, :]

tensor([1, 2, 3])

In [172]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3,6, 9
print (x[:,:, 2])

tensor(9)
tensor([[3, 6, 9]])
