<a href="https://colab.research.google.com/github/shahrukhalam1011-unisa/Pytorch_learning_free_code_camp/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating tensors

Pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [5]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [6]:
scalar.ndim

0

In [7]:
# Get tensor back as Python int
scalar.item()

7

In [8]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [9]:
vector.ndim

1

In [10]:
vector.shape

torch.Size([2])

In [14]:
#Matrix
Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [19]:
Matrix[1]

tensor([ 9, 10])

In [15]:
Matrix.ndim

2

In [16]:
Matrix.shape

torch.Size([2, 2])

In [17]:
# Tensor
Tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [18]:
Tensor.ndim

3