<a href="https://colab.research.google.com/github/shahrukhalam1011-unisa/Pytorch_learning_free_code_camp/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [188]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating tensors

Pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [189]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [190]:
scalar.ndim

0

In [191]:
# Get tensor back as Python int
scalar.item()

7

In [192]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [193]:
vector.ndim

1

In [194]:
vector.shape

torch.Size([2])

In [195]:
#Matrix
Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [196]:
Matrix[1]

tensor([ 9, 10])

In [197]:
Matrix.ndim

2

In [198]:
Matrix.shape

torch.Size([2, 2])

In [199]:
# Tensor
Tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [200]:
Tensor.ndim

3

In [201]:
Tensor.shape

torch.Size([1, 3, 3])

In [202]:
Tensor2=torch.tensor([[[1,2,3,3,3],[2,3,5,3,4],[1,2,1,2,5],[2,3,5,6,1]]])

In [203]:
Tensor2

tensor([[[1, 2, 3, 3, 3],
         [2, 3, 5, 3, 4],
         [1, 2, 1, 2, 5],
         [2, 3, 5, 6, 1]]])

In [204]:
Tensor2.shape

torch.Size([1, 4, 5])

### Random tensors

Required since to start with random numbers and update to better represent the data

In [205]:
## Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5171, 0.6231, 0.2108, 0.2031],
        [0.2332, 0.9049, 0.3465, 0.7164],
        [0.7801, 0.9004, 0.9806, 0.9059]])

In [206]:
random_tensor2=torch.rand(2,3,10)

In [207]:
random_tensor2

tensor([[[0.0756, 0.6516, 0.8026, 0.7824, 0.0442, 0.8219, 0.0204, 0.4351,
          0.1014, 0.4232],
         [0.0093, 0.0584, 0.1769, 0.6879, 0.5258, 0.5293, 0.0814, 0.2703,
          0.2632, 0.2379],
         [0.4933, 0.1916, 0.8382, 0.7242, 0.5128, 0.8765, 0.8252, 0.4306,
          0.7766, 0.3150]],

        [[0.6762, 0.7396, 0.8207, 0.4263, 0.4606, 0.6741, 0.8358, 0.2121,
          0.0322, 0.2415],
         [0.1684, 0.4019, 0.0866, 0.2767, 0.7944, 0.9776, 0.6815, 0.4272,
          0.7575, 0.6149],
         [0.2285, 0.3682, 0.0388, 0.7422, 0.6135, 0.9870, 0.1590, 0.1305,
          0.4798, 0.0945]]])

In [208]:
random_tensor2.shape

torch.Size([2, 3, 10])

In [209]:
random_tensor2.ndim

3

In [210]:
random_tensor3=torch.rand(200,344,100)

In [211]:
random_tensor3

tensor([[[0.6163, 0.9879, 0.1173,  ..., 0.0544, 0.2719, 0.8553],
         [0.0547, 0.8251, 0.2828,  ..., 0.8234, 0.7579, 0.0852],
         [0.8564, 0.7718, 0.9200,  ..., 0.0975, 0.3436, 0.3587],
         ...,
         [0.5062, 0.4041, 0.3717,  ..., 0.2892, 0.2677, 0.2943],
         [0.0828, 0.6850, 0.4448,  ..., 0.9602, 0.2674, 0.8092],
         [0.4836, 0.3652, 0.8966,  ..., 0.6052, 0.3965, 0.5757]],

        [[0.6866, 0.6815, 0.9323,  ..., 0.3053, 0.4039, 0.6462],
         [0.7640, 0.2789, 0.5277,  ..., 0.8802, 0.3009, 0.0475],
         [0.7904, 0.6641, 0.8584,  ..., 0.9435, 0.6155, 0.8084],
         ...,
         [0.9466, 0.6548, 0.0867,  ..., 0.9963, 0.8036, 0.8703],
         [0.5236, 0.1560, 0.4145,  ..., 0.7689, 0.5338, 0.1827],
         [0.7222, 0.7793, 0.3498,  ..., 0.9752, 0.5436, 0.1609]],

        [[0.6033, 0.9406, 0.4601,  ..., 0.5191, 0.3270, 0.7501],
         [0.1927, 0.9064, 0.2667,  ..., 0.3163, 0.3693, 0.1451],
         [0.7159, 0.0054, 0.9473,  ..., 0.0947, 0.8806, 0.

In [212]:
random_tensor3.shape

torch.Size([200, 344, 100])

In [213]:
random_tensor3.ndim

3

In [214]:
random_tensor4=torch.rand(3,2,5,5)

In [215]:
random_tensor4

tensor([[[[0.6929, 0.5328, 0.3939, 0.8238, 0.6151],
          [0.2563, 0.1753, 0.0665, 0.1514, 0.1087],
          [0.5058, 0.8085, 0.9790, 0.8817, 0.1890],
          [0.9150, 0.6080, 0.5719, 0.8843, 0.9519],
          [0.4485, 0.3353, 0.5134, 0.8633, 0.7027]],

         [[0.7873, 0.9176, 0.7584, 0.9102, 0.5876],
          [0.4208, 0.5751, 0.4112, 0.3617, 0.1590],
          [0.8186, 0.7522, 0.0043, 0.3347, 0.5934],
          [0.3688, 0.1030, 0.4225, 0.3013, 0.2990],
          [0.4487, 0.3209, 0.8387, 0.7823, 0.4556]]],


        [[[0.3930, 0.7958, 0.3698, 0.6981, 0.6665],
          [0.2301, 0.7221, 0.9352, 0.7793, 0.7164],
          [0.9353, 0.3549, 0.1619, 0.8171, 0.5415],
          [0.8869, 0.1359, 0.8052, 0.8200, 0.8935],
          [0.7719, 0.4749, 0.4311, 0.2047, 0.1801]],

         [[0.5095, 0.8913, 0.9620, 0.9810, 0.0482],
          [0.0341, 0.4078, 0.2172, 0.4742, 0.6281],
          [0.8429, 0.0871, 0.7349, 0.6162, 0.4063],
          [0.3771, 0.7054, 0.6235, 0.0752, 0.2213],
    

In [216]:
random_tensor4.ndim

4

In [217]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) # colour channel, height, width

In [218]:
random_image_size_tensor

tensor([[[6.7231e-01, 3.3584e-01, 8.9346e-01,  ..., 9.7069e-01,
          6.1053e-01, 1.7418e-01],
         [8.5834e-01, 4.8034e-01, 3.3559e-01,  ..., 2.6116e-02,
          8.6313e-01, 5.2738e-01],
         [9.2035e-01, 8.5595e-01, 4.9174e-01,  ..., 9.7863e-03,
          6.0980e-01, 2.0310e-01],
         ...,
         [7.3422e-01, 8.2593e-01, 8.0287e-01,  ..., 6.9743e-01,
          4.4221e-01, 5.5844e-01],
         [3.6876e-01, 2.8604e-01, 2.0489e-01,  ..., 5.4430e-01,
          1.9217e-01, 7.1993e-01],
         [8.2178e-02, 4.6372e-01, 2.4916e-01,  ..., 4.0226e-01,
          5.5841e-01, 5.3683e-01]],

        [[7.1354e-01, 9.4780e-01, 8.5947e-02,  ..., 6.0146e-01,
          8.7530e-01, 5.7043e-01],
         [5.1295e-01, 8.4972e-01, 8.7186e-01,  ..., 4.8246e-01,
          1.8798e-01, 4.6842e-01],
         [5.9705e-01, 3.7840e-01, 9.0804e-01,  ..., 6.3056e-04,
          2.1874e-01, 4.3852e-02],
         ...,
         [4.0990e-01, 4.2090e-01, 5.8550e-01,  ..., 6.9677e-01,
          4.111

### Zeroes and ones

In [219]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,224,224))
ones=torch.ones(size=(3,224,224))

In [220]:
zeros
ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [221]:
zeros*random_image_size_tensor

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [222]:
ones*random_image_size_tensor

tensor([[[6.7231e-01, 3.3584e-01, 8.9346e-01,  ..., 9.7069e-01,
          6.1053e-01, 1.7418e-01],
         [8.5834e-01, 4.8034e-01, 3.3559e-01,  ..., 2.6116e-02,
          8.6313e-01, 5.2738e-01],
         [9.2035e-01, 8.5595e-01, 4.9174e-01,  ..., 9.7863e-03,
          6.0980e-01, 2.0310e-01],
         ...,
         [7.3422e-01, 8.2593e-01, 8.0287e-01,  ..., 6.9743e-01,
          4.4221e-01, 5.5844e-01],
         [3.6876e-01, 2.8604e-01, 2.0489e-01,  ..., 5.4430e-01,
          1.9217e-01, 7.1993e-01],
         [8.2178e-02, 4.6372e-01, 2.4916e-01,  ..., 4.0226e-01,
          5.5841e-01, 5.3683e-01]],

        [[7.1354e-01, 9.4780e-01, 8.5947e-02,  ..., 6.0146e-01,
          8.7530e-01, 5.7043e-01],
         [5.1295e-01, 8.4972e-01, 8.7186e-01,  ..., 4.8246e-01,
          1.8798e-01, 4.6842e-01],
         [5.9705e-01, 3.7840e-01, 9.0804e-01,  ..., 6.3056e-04,
          2.1874e-01, 4.3852e-02],
         ...,
         [4.0990e-01, 4.2090e-01, 5.8550e-01,  ..., 6.9677e-01,
          4.111

### Creating a range of tensors and tensors-like

In [223]:
#Use torch.arange()
torch.arange(1,11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [224]:
one_to_ten=torch.arange(start=1, end=10, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [225]:
#Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)

In [226]:
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [227]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16 #what datatype is the tensor
                             , device=None # Device tensor is on
                             ,
                             requires_grad=False # Whether to track gradient for the tensor
                             )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [228]:
new_int_tensor_train=torch.rand(3,4)

In [229]:
new_int_tensor_train

tensor([[0.7723, 0.7515, 0.6477, 0.8117],
        [0.7533, 0.0176, 0.6170, 0.9605],
        [0.8636, 0.1910, 0.7271, 0.9177]])

In [230]:
# Find details of tensor

print(f"Datatype is: {new_int_tensor_train.dtype}")
print(f"Shape is: {new_int_tensor_train.shape}")
print(f"Device is: {new_int_tensor_train.device}")

Datatype is: torch.float32
Shape is: torch.Size([3, 4])
Device is: cpu


In [231]:
# Change data type
change_new_int_tensor_train=new_int_tensor_train.to(torch.float16)
change_new_int_tensor_train

tensor([[0.7725, 0.7515, 0.6475, 0.8115],
        [0.7534, 0.0176, 0.6172, 0.9604],
        [0.8638, 0.1910, 0.7271, 0.9175]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

### Matrix multiplication

Two ways:
1. Element-wise multiplication
2. Matrix Multiplication




In [232]:
tensor1=torch.rand(3,6,5)
tensor2=torch.rand(1,5,7)
tensor1
tensor2

tensor([[[0.5911, 0.5377, 0.4924, 0.9721, 0.9265, 0.7610, 0.7758],
         [0.7245, 0.0019, 0.8647, 0.2973, 0.8680, 0.5597, 0.0253],
         [0.3748, 0.6516, 0.2832, 0.5431, 0.1539, 0.0505, 0.4156],
         [0.0284, 0.6535, 0.5802, 0.3887, 0.0419, 0.8700, 0.1058],
         [0.2308, 0.5740, 0.1671, 0.2685, 0.4550, 0.9625, 0.0056]]])

In [233]:
#Matrix multiplication
product_ten=torch.matmul(tensor1, tensor2)
product_ten

tensor([[[1.0859, 1.2648, 1.0809, 1.3074, 1.2447, 1.3462, 0.7819],
         [1.3589, 1.6060, 1.6119, 1.5847, 1.6218, 2.0555, 0.8138],
         [1.3756, 1.3635, 1.9404, 1.6710, 1.8995, 2.4344, 0.8483],
         [1.1909, 1.0923, 1.3939, 1.1587, 1.5256, 1.8077, 0.5017],
         [0.8945, 1.4636, 1.1548, 1.3182, 1.3077, 2.1246, 0.6535],
         [0.4021, 0.6550, 0.5928, 0.5509, 0.5838, 1.0285, 0.2214]],

        [[0.5552, 0.9869, 0.8734, 0.7967, 0.8602, 1.6276, 0.2924],
         [1.0460, 1.8469, 1.3749, 1.5610, 1.2093, 2.0318, 0.8257],
         [1.0689, 1.1446, 1.3165, 1.0441, 1.1520, 1.4393, 0.4406],
         [0.6850, 0.7275, 0.6189, 1.0534, 1.0640, 1.0747, 0.7552],
         [1.0532, 1.0879, 1.3568, 1.0477, 1.3660, 1.8392, 0.3909],
         [1.2034, 1.6180, 1.6490, 1.7646, 1.4245, 1.8918, 1.0651]],

        [[1.2055, 1.0583, 1.3019, 1.0759, 1.3581, 1.4214, 0.4814],
         [0.8953, 0.9835, 1.0718, 1.1656, 1.2287, 1.4846, 0.6737],
         [1.1281, 1.1677, 1.5426, 1.2387, 1.3830, 1.7904, 

In [234]:
changed_to_int32=product_ten.to(torch.int32)
changed_to_int32

tensor([[[1, 1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 2, 0],
         [1, 1, 1, 1, 1, 2, 0],
         [1, 1, 1, 1, 1, 1, 0],
         [0, 1, 1, 1, 1, 2, 0],
         [0, 0, 0, 0, 0, 1, 0]],

        [[0, 0, 0, 0, 0, 1, 0],
         [1, 1, 1, 1, 1, 2, 0],
         [1, 1, 1, 1, 1, 1, 0],
         [0, 0, 0, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 1]],

        [[1, 1, 1, 1, 1, 1, 0],
         [0, 0, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 0],
         [0, 1, 1, 1, 1, 1, 0],
         [1, 1, 1, 1, 1, 1, 0],
         [0, 0, 1, 0, 0, 1, 0]]], dtype=torch.int32)

### Most common error in Deep Learning: Shape error

1. The inner dimension must match
2. The resulting matrix would be the outer dimension
3. In case, the tensors violate rules 1 and 2, tensor manipulation i.e. transpose can be used. It works by switching axes.

In [235]:
Tensor_A=torch.tensor([[1,2],[3,4],[5,6]])
Tensor_B=torch.tensor([[5,3],[2,6],[1,8]])
Tensor_A
Tensor_B
Tensor_A.shape
Tensor_B.shape
Tensor_C=torch.matmul(Tensor_A,Tensor_B)
Tensor_C

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [236]:
# To resolve the above use transpose
Trans_Tensor_B=Tensor_B.T
Trans_Tensor_B

tensor([[5, 2, 1],
        [3, 6, 8]])

In [237]:
Tensor_C=torch.matmul(Tensor_A,Trans_Tensor_B)
Tensor_C

tensor([[11, 14, 17],
        [27, 30, 35],
        [43, 46, 53]])

In [238]:
Tensor_A.shape
Trans_Tensor_B.shape

torch.Size([2, 3])

### Position of Tensor elements (pixels, data etc)

In [239]:
tensor_4D=torch.rand(3,6,2,1)
tensor_4D

tensor([[[[0.2216],
          [0.3153]],

         [[0.6466],
          [0.9978]],

         [[0.0865],
          [0.4641]],

         [[0.3623],
          [0.8710]],

         [[0.4526],
          [0.4830]],

         [[0.0354],
          [0.4828]]],


        [[[0.2480],
          [0.7569]],

         [[0.7820],
          [0.9949]],

         [[0.0045],
          [0.6014]],

         [[0.5795],
          [0.9924]],

         [[0.1128],
          [0.7135]],

         [[0.6700],
          [0.6137]]],


        [[[0.1604],
          [0.9513]],

         [[0.9152],
          [0.5119]],

         [[0.1887],
          [0.7121]],

         [[0.0911],
          [0.0075]],

         [[0.4027],
          [0.7819]],

         [[0.4399],
          [0.4332]]]])

In [240]:
position_min=tensor_4D.argmin()

In [241]:
position_min

tensor(16)

In [242]:
position_max=tensor_4D.argmax()
position_max

tensor(3)

### Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack)
* Squeeze - removes all 1 dimensions from a tensor
* Unsqueeze - add a 1 dimension to a target tensor
*Permute - Return a view of the input with dimensions permuted (swapped) in a certain way

In [263]:
x=torch.arange(2., 10.)
x, x.shape

(tensor([2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([8]))

In [264]:
# Add an extra dimension (note that the size must match i.e. 4*2 or 2*4 = 8)
x_reshaped=x.reshape(4,2)
print(x_reshaped, x_reshaped.shape)
x_reshaped2=x.reshape(2,4)
print(x_reshaped2, x_reshaped.shape)

tensor([[2., 3.],
        [4., 5.],
        [6., 7.],
        [8., 9.]]) torch.Size([4, 2])
tensor([[2., 3., 4., 5.],
        [6., 7., 8., 9.]]) torch.Size([4, 2])


In [267]:
# Change the view
z=x.view(1,8)
z, z.shape

(tensor([[2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 8]))

In [268]:
# Changing z changes x (due to view of a tensor sharing same memory)
z[:,0] = 5
z, x

(tensor([[5., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 3., 4., 5., 6., 7., 8., 9.]))