<a href="https://colab.research.google.com/github/shahrukhalam1011-unisa/Pytorch_learning_free_code_camp/blob/main/Pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.6.0+cu124


# Introduction to Tensors

## Creating tensors

Pytorch tensors are created using torch.Tensor() = https://docs.pytorch.org/docs/stable/tensors.html

In [3]:
# scalar
scalar=torch.tensor(7)
scalar

tensor(7)

In [4]:
scalar.ndim

0

In [5]:
# Get tensor back as Python int
scalar.item()

7

In [6]:
#Vector
vector=torch.tensor([7,7])
vector

tensor([7, 7])

In [7]:
vector.ndim

1

In [8]:
vector.shape

torch.Size([2])

In [9]:
#Matrix
Matrix=torch.tensor([[7,8],[9,10]])
Matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [10]:
Matrix[1]

tensor([ 9, 10])

In [11]:
Matrix.ndim

2

In [12]:
Matrix.shape

torch.Size([2, 2])

In [13]:
# Tensor
Tensor=torch.tensor([[[1,2,3],[3,6,9],[2,4,5]]])
Tensor

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
Tensor.ndim

3

In [15]:
Tensor.shape

torch.Size([1, 3, 3])

In [30]:
Tensor2=torch.tensor([[[1,2,3,3,3],[2,3,5,3,4],[1,2,1,2,5],[2,3,5,6,1]]])

In [31]:
Tensor2

tensor([[[1, 2, 3, 3, 3],
         [2, 3, 5, 3, 4],
         [1, 2, 1, 2, 5],
         [2, 3, 5, 6, 1]]])

In [32]:
Tensor2.shape

torch.Size([1, 4, 5])

### Random tensors

Required since to start with random numbers and update to better represent the data

In [34]:
## Create a random tensor of size (3,4)
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.5701, 0.9775, 0.9378, 0.7571],
        [0.5929, 0.9632, 0.5358, 0.2446],
        [0.3716, 0.1551, 0.4939, 0.3036]])

In [55]:
random_tensor2=torch.rand(2,3,10)

In [56]:
random_tensor2

tensor([[[0.4076, 0.2443, 0.3822, 0.8215, 0.9931, 0.3449, 0.2001, 0.6481,
          0.3784, 0.7524],
         [0.1401, 0.9705, 0.5165, 0.0188, 0.5203, 0.2147, 0.6944, 0.6136,
          0.4964, 0.8645],
         [0.1772, 0.6129, 0.7421, 0.8529, 0.3135, 0.7705, 0.1364, 0.8229,
          0.3001, 0.5958]],

        [[0.2647, 0.7246, 0.2322, 0.1873, 0.9583, 0.3070, 0.9131, 0.2006,
          0.0540, 0.5314],
         [0.3626, 0.0658, 0.0270, 0.7768, 0.0230, 0.0423, 0.7216, 0.6597,
          0.6531, 0.3082],
         [0.6127, 0.4484, 0.2760, 0.6984, 0.3189, 0.5062, 0.6720, 0.8024,
          0.5925, 0.9483]]])

In [57]:
random_tensor2.shape

torch.Size([2, 3, 10])

In [58]:
random_tensor2.ndim

3

In [59]:
random_tensor3=torch.rand(200,344,100)

In [60]:
random_tensor3

tensor([[[0.5227, 0.6097, 0.5507,  ..., 0.1372, 0.7805, 0.4787],
         [0.6783, 0.7736, 0.8364,  ..., 0.6540, 0.2964, 0.9194],
         [0.6374, 0.9891, 0.1691,  ..., 0.7022, 0.0647, 0.5260],
         ...,
         [0.0115, 0.7482, 0.5416,  ..., 0.9812, 0.0243, 0.0284],
         [0.3053, 0.3461, 0.2353,  ..., 0.0046, 0.0541, 0.2628],
         [0.5859, 0.7425, 0.3896,  ..., 0.0019, 0.7070, 0.2891]],

        [[0.2071, 0.2755, 0.7452,  ..., 0.5087, 0.1254, 0.1422],
         [0.3230, 0.8034, 0.5950,  ..., 0.8821, 0.2322, 0.6115],
         [0.7193, 0.2949, 0.1087,  ..., 0.0041, 0.4255, 0.6030],
         ...,
         [0.1046, 0.6646, 0.7836,  ..., 0.8120, 0.8077, 0.4540],
         [0.3061, 0.8489, 0.4292,  ..., 0.7818, 0.7035, 0.1212],
         [0.8316, 0.0311, 0.2770,  ..., 0.9598, 0.1061, 0.6383]],

        [[0.1661, 0.3738, 0.8618,  ..., 0.0763, 0.8100, 0.8517],
         [0.1235, 0.8796, 0.2982,  ..., 0.9844, 0.4385, 0.6347],
         [0.4233, 0.4051, 0.3088,  ..., 0.0549, 0.9240, 0.

In [61]:
random_tensor3.shape

torch.Size([200, 344, 100])

In [62]:
random_tensor3.ndim

3

In [63]:
random_tensor4=torch.rand(3,2,5,5)

In [64]:
random_tensor4

tensor([[[[0.8105, 0.1696, 0.4396, 0.7134, 0.7199],
          [0.7365, 0.2711, 0.7866, 0.9120, 0.5788],
          [0.6004, 0.0851, 0.9694, 0.8684, 0.6853],
          [0.6326, 0.5768, 0.7781, 0.4285, 0.4809],
          [0.2187, 0.1240, 0.3582, 0.3492, 0.4657]],

         [[0.1802, 0.8538, 0.6708, 0.7755, 0.5669],
          [0.4642, 0.3862, 0.9898, 0.8113, 0.6089],
          [0.3604, 0.4349, 0.8946, 0.1743, 0.0571],
          [0.0418, 0.2414, 0.8715, 0.3149, 0.4794],
          [0.2571, 0.4473, 0.5116, 0.2971, 0.2906]]],


        [[[0.2208, 0.4677, 0.3863, 0.5406, 0.5644],
          [0.5312, 0.0417, 0.9344, 0.1419, 0.3999],
          [0.4224, 0.5810, 0.4463, 0.8160, 0.1581],
          [0.6334, 0.6439, 0.7193, 0.8538, 0.4542],
          [0.5454, 0.1149, 0.8001, 0.6553, 0.6790]],

         [[0.0638, 0.9651, 0.5459, 0.0425, 0.0691],
          [0.3706, 0.9886, 0.1226, 0.8645, 0.2201],
          [0.9342, 0.2609, 0.0522, 0.9343, 0.8446],
          [0.7232, 0.6476, 0.0777, 0.6192, 0.3985],
    

In [65]:
random_tensor4.ndim

4

In [68]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor=torch.rand(size=(3,224,224)) # colour channel, height, width

In [69]:
random_image_size_tensor

tensor([[[0.2292, 0.4739, 0.5221,  ..., 0.7601, 0.6934, 0.9427],
         [0.1417, 0.1842, 0.4154,  ..., 0.6140, 0.5959, 0.9978],
         [0.6442, 0.0191, 0.8151,  ..., 0.2604, 0.4768, 0.2896],
         ...,
         [0.1894, 0.4683, 0.3957,  ..., 0.4721, 0.2885, 0.4186],
         [0.9078, 0.2755, 0.4197,  ..., 0.5812, 0.0643, 0.2363],
         [0.7819, 0.3909, 0.2402,  ..., 0.3241, 0.2246, 0.4326]],

        [[0.9764, 0.4064, 0.3349,  ..., 0.1565, 0.6356, 0.4457],
         [0.9977, 0.8083, 0.8133,  ..., 0.5199, 0.9821, 0.0774],
         [0.1756, 0.8394, 0.8904,  ..., 0.3457, 0.8507, 0.0347],
         ...,
         [0.6930, 0.9103, 0.4138,  ..., 0.2047, 0.1223, 0.2961],
         [0.6925, 0.2776, 0.3100,  ..., 0.5552, 0.5215, 0.6500],
         [0.8091, 0.0599, 0.6870,  ..., 0.2920, 0.9925, 0.3665]],

        [[0.8608, 0.1821, 0.9473,  ..., 0.8234, 0.5772, 0.4541],
         [0.2332, 0.9744, 0.5916,  ..., 0.0984, 0.8534, 0.3603],
         [0.0917, 0.1364, 0.8104,  ..., 0.4415, 0.5448, 0.

### Zeroes and ones

In [93]:
#Create a tensor of all zeros
zeros=torch.zeros(size=(3,224,224))
ones=torch.ones(size=(3,224,224))

In [94]:
zeros
ones

tensor([[[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]],

        [[1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         ...,
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.],
         [1., 1., 1.,  ..., 1., 1., 1.]]])

In [95]:
zeros*random_image_size_tensor

tensor([[[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]],

        [[0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         ...,
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.],
         [0., 0., 0.,  ..., 0., 0., 0.]]])

In [96]:
ones*random_image_size_tensor

tensor([[[0.2292, 0.4739, 0.5221,  ..., 0.7601, 0.6934, 0.9427],
         [0.1417, 0.1842, 0.4154,  ..., 0.6140, 0.5959, 0.9978],
         [0.6442, 0.0191, 0.8151,  ..., 0.2604, 0.4768, 0.2896],
         ...,
         [0.1894, 0.4683, 0.3957,  ..., 0.4721, 0.2885, 0.4186],
         [0.9078, 0.2755, 0.4197,  ..., 0.5812, 0.0643, 0.2363],
         [0.7819, 0.3909, 0.2402,  ..., 0.3241, 0.2246, 0.4326]],

        [[0.9764, 0.4064, 0.3349,  ..., 0.1565, 0.6356, 0.4457],
         [0.9977, 0.8083, 0.8133,  ..., 0.5199, 0.9821, 0.0774],
         [0.1756, 0.8394, 0.8904,  ..., 0.3457, 0.8507, 0.0347],
         ...,
         [0.6930, 0.9103, 0.4138,  ..., 0.2047, 0.1223, 0.2961],
         [0.6925, 0.2776, 0.3100,  ..., 0.5552, 0.5215, 0.6500],
         [0.8091, 0.0599, 0.6870,  ..., 0.2920, 0.9925, 0.3665]],

        [[0.8608, 0.1821, 0.9473,  ..., 0.8234, 0.5772, 0.4541],
         [0.2332, 0.9744, 0.5916,  ..., 0.0984, 0.8534, 0.3603],
         [0.0917, 0.1364, 0.8104,  ..., 0.4415, 0.5448, 0.

### Creating a range of tensors and tensors-like

In [97]:
#Use torch.arange()
torch.arange(1,11)


tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [98]:
one_to_ten=torch.arange(start=1, end=10, step=2)
one_to_ten

tensor([1, 3, 5, 7, 9])

In [99]:
#Creating tensors like
ten_zeros=torch.zeros_like(input=one_to_ten)

In [100]:
ten_zeros

tensor([0, 0, 0, 0, 0])

### Tensor datatypes

In [112]:
# Float 32 tensor
float_32_tensor=torch.tensor([3.0,6.0,9.0], dtype=torch.float16 #what datatype is the tensor
                             , device=None # Device tensor is on
                             ,
                             requires_grad=False # Whether to track gradient for the tensor
                             )
float_32_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [128]:
new_int_tensor_train=torch.rand(3,4)

In [129]:
new_int_tensor_train

tensor([[0.7490, 0.6431, 0.3001, 0.8106],
        [0.4842, 0.4442, 0.8922, 0.1358],
        [0.3437, 0.5209, 0.4544, 0.4313]])

In [132]:
# Find details of tensor

print(f"Datatype is: {new_int_tensor_train.dtype}")
print(f"Shape is: {new_int_tensor_train.shape}")
print(f"Device is: {new_int_tensor_train.device}")

Datatype is: torch.float32
Shape is: torch.Size([3, 4])
Device is: cpu


In [135]:
# Change data type
change_new_int_tensor_train=new_int_tensor_train.to(torch.float16)
change_new_int_tensor_train

tensor([[0.7490, 0.6431, 0.3000, 0.8105],
        [0.4841, 0.4441, 0.8921, 0.1357],
        [0.3438, 0.5210, 0.4543, 0.4312]], dtype=torch.float16)

### Manipulating Tensors (tensor operations)

Tensor operations:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

### Matrix multiplication

Two ways:
1. Element-wise multiplication
2. Matrix Multiplication




In [159]:
tensor1=torch.rand(3,6,5)
tensor2=torch.rand(1,5,7)
tensor1
tensor2

tensor([[[0.6129, 0.9320, 0.0556, 0.8165, 0.9090, 0.2598, 0.9403],
         [0.7089, 0.6851, 0.5877, 0.4151, 0.6725, 0.8502, 0.0209],
         [0.4517, 0.4271, 0.1781, 0.4940, 0.0067, 0.1559, 0.0946],
         [0.3610, 0.0513, 0.6804, 0.6896, 0.5020, 0.8321, 0.4057],
         [0.4360, 0.1643, 0.3302, 0.9462, 0.9120, 0.1140, 0.5942]]])

In [160]:
#Matrix multiplication
product_ten=torch.matmul(tensor1, tensor2)
product_ten

tensor([[[0.9449, 0.6327, 0.7965, 1.4753, 1.2052, 0.8054, 0.8491],
         [1.3661, 1.1769, 0.8811, 1.7882, 1.4016, 0.9623, 0.9676],
         [1.1146, 0.9943, 0.7545, 1.5192, 1.2678, 0.9007, 0.9625],
         [1.3059, 0.9031, 1.2118, 1.7623, 1.6051, 1.3725, 0.9113],
         [1.2054, 0.8812, 0.9482, 1.7982, 1.6285, 0.9780, 1.0720],
         [1.1144, 0.9659, 0.7008, 1.5252, 1.0301, 0.7648, 0.8481]],

        [[1.4432, 1.4896, 0.8184, 1.8835, 1.5796, 1.1111, 1.3469],
         [1.7124, 1.5051, 1.3394, 2.0884, 1.6681, 1.7311, 1.1683],
         [1.0305, 0.9571, 0.8144, 1.1743, 1.2946, 1.1087, 0.7434],
         [0.9995, 0.9516, 0.6911, 0.9997, 1.0205, 0.9091, 0.4760],
         [1.6216, 1.6872, 0.9093, 1.7341, 1.6803, 1.2336, 1.0233],
         [1.3283, 1.1308, 0.8697, 1.7093, 1.3404, 0.9440, 0.8849]],

        [[1.2261, 1.3764, 0.6976, 1.1041, 1.2730, 1.0802, 0.6683],
         [1.0916, 0.7733, 0.8653, 1.5889, 1.3921, 0.8687, 0.8690],
         [1.9192, 1.6723, 1.3942, 2.4551, 2.1236, 1.6901, 

In [162]:
changed_to_int32=product_ten.to(torch.int32)
changed_to_int32

tensor([[[0, 0, 0, 1, 1, 0, 0],
         [1, 1, 0, 1, 1, 0, 0],
         [1, 0, 0, 1, 1, 0, 0],
         [1, 0, 1, 1, 1, 1, 0],
         [1, 0, 0, 1, 1, 0, 1],
         [1, 0, 0, 1, 1, 0, 0]],

        [[1, 1, 0, 1, 1, 1, 1],
         [1, 1, 1, 2, 1, 1, 1],
         [1, 0, 0, 1, 1, 1, 0],
         [0, 0, 0, 0, 1, 0, 0],
         [1, 1, 0, 1, 1, 1, 1],
         [1, 1, 0, 1, 1, 0, 0]],

        [[1, 1, 0, 1, 1, 1, 0],
         [1, 0, 0, 1, 1, 0, 0],
         [1, 1, 1, 2, 2, 1, 1],
         [2, 1, 1, 2, 2, 1, 1],
         [0, 0, 0, 1, 0, 0, 0],
         [1, 1, 1, 1, 1, 1, 1]]], dtype=torch.int32)

### Most common error in Deep Learning: Shape error

1. The inner dimension must match
2. The resulting matrix would be the outer dimension
3. In case, the tensors violate rules 1 and 2, tensor manipulation i.e. transpose can be used. It works by switching axes.